server.port = 8081

spring.datasource.url= jdbc:postgresql://localhost:5432/Auth-service
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true



jwt.secret=Thisisasecretekeytextwshichisusedtovalidatethetokenfrauthentication

eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka


spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# expose actuator endpoints
management.endpoints.web.exposure.include=*

# show full health details
management.endpoint.health.show-details=always
eureka.client.healthcheck.enabled=true
