server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/catalog-service
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Thisisasecretekeytextwshichisusedtovalidatethetokenfrauthentication

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.healthcheck.enabled=true

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
